// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwvfidCEamvwCJ3j23PJJTf5aiKW102Zc',
    appId: '1:597658737138:web:90a5c0fe196443b76c736b',
    messagingSenderId: '597658737138',
    projectId: 'code-learning-app-fa86a',
    authDomain: 'code-learning-app-fa86a.firebaseapp.com',
    storageBucket: 'code-learning-app-fa86a.firebasestorage.app',
    measurementId: 'G-HBQKRVELQX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbhFHN0YPU0Ej_XicsR4oR07nsDkOsd98',
    appId: '1:597658737138:android:a9b6e71dc168a74b6c736b',
    messagingSenderId: '597658737138',
    projectId: 'code-learning-app-fa86a',
    storageBucket: 'code-learning-app-fa86a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYhcd8OhpO2HrWjpV58Orz6Tb9xmumrIE',
    appId: '1:597658737138:ios:9cf6100d509ae5ee6c736b',
    messagingSenderId: '597658737138',
    projectId: 'code-learning-app-fa86a',
    storageBucket: 'code-learning-app-fa86a.firebasestorage.app',
    iosBundleId: 'com.example.codeLearningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYhcd8OhpO2HrWjpV58Orz6Tb9xmumrIE',
    appId: '1:597658737138:ios:9cf6100d509ae5ee6c736b',
    messagingSenderId: '597658737138',
    projectId: 'code-learning-app-fa86a',
    storageBucket: 'code-learning-app-fa86a.firebasestorage.app',
    iosBundleId: 'com.example.codeLearningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwvfidCEamvwCJ3j23PJJTf5aiKW102Zc',
    appId: '1:597658737138:web:570155f977066e736c736b',
    messagingSenderId: '597658737138',
    projectId: 'code-learning-app-fa86a',
    authDomain: 'code-learning-app-fa86a.firebaseapp.com',
    storageBucket: 'code-learning-app-fa86a.firebasestorage.app',
    measurementId: 'G-3DL2B1GV1F',
  );
}
